external_components:
  source: components

esphome:
  name: my-device

esp32:
  variant: esp32c6

i2c:
  sda: 6
  scl: 7
  scan: true

sensor:

as7341:
  id: elespectrometro
  address: 0x39  # optional

logger:
  level: VERY_VERBOSE # Options: NONE, ERROR, WARN, INFO, DEBUG, VERBOSE, VERY_VERBOSE
  # baud_rate: 0 # Uncomment to disable serial loggingr