substitutions:
  device_name: test-esp32c6
  friendly_name: "Espectrometro AS7341"

external_components:
  - source: 
      type: local
      path: components

esphome:
  name: espectrometro-as7341
  includes:
   - lib/Constantes.h
   - lib/calculoCircadiano.h
   - lib/procesarEspectro.h
   - lib/calculoColorimetria.h
   - lib/calculoColorimetria.cpp

esp32:
  variant: esp32c6
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

i2c:
  id: bus_i2c
  sda: 6
  scl: 7
  scan: true

sensor:
  - platform: as7341
    id: elespectrometro
    address: 0x39  # I2C Address Según Datasheet (Opcional)
    i2c_id: bus_i2c
    update_interval: 500ms
    lux:
      name: "lux"
      id: sensor_lux
    medi:
      name: "Melanopic EDI"
      id: sensor_medi
    cct:
      name: "CCT"
      id: sensor_cct
    duv:
      name: "Duv"
      id: sensor_duv
    x:
      name: "Chromaticity x"
      id: sensor_cie_x
    y:
      name: "Chromaticity y"
      id: sensor_cie_y
    ra:
      name: "CRI Ra"
      id: sensor_ra
    CLa:
      name: "CLa"
      id: sensor_CLa
    CS:
      name: "CS"
      id: sensor_CS

logger:
  level: DEBUG # Options: NONE, ERROR, WARN, INFO, DEBUG, VERBOSE, VERY_VERBOSE
  # baud_rate: 0 # Uncomment to disable serial loggingr
  
uart:
    id: uart_bus
    tx_pin: GPIO21 # Ajusta a tus pines reales del C6
    rx_pin: GPIO20
    baud_rate: 115200

wifi:
  ssid: "GATITOS"
  password: "Katos25*"

  enable_on_boot: true
  fast_connect: true

  power_save_mode: none

  ap:
  #  ssid: !secret wifi_ssid
  #  password: "12345678"

captive_portal:
  
api:

ota:
  - platform: esphome
    password: "tu_password_ota"
