external_components:
  source: components

esphome:
  name: my-device
  includes:
   - Constantes.h
   - procesarEspectro.h

esp32:
  variant: esp32c6

i2c:
  sda: 6
  scl: 7
  scan: true

sensor:

as7341:
  id: elespectrometro
  address: 0x39  # I2C Address Según Datasheet (Opcional)


logger:
  level: DEBUG # Options: NONE, ERROR, WARN, INFO, DEBUG, VERBOSE, VERY_VERBOSE
  # baud_rate: 0 # Uncomment to disable serial loggingr
  
uart:
    id: uart_bus
    tx_pin: GPIO21 # Ajusta a tus pines reales del C6
    rx_pin: GPIO20
    baud_rate: 115200
  